# Add your details
spring:   
  data:
    mongodb:
      host: localhost
      database: hotel-management
      port: 27017
      
  logging:
    level:'[org.springframework.data.mongodb]': debug
    
  boot:
    admin:
      client:
        url: http://localhost:9494
      
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    
    
