# Add your details
spring:
  application:
    name: admin-server
    
  data:
    mongodb:
      host: localhost
      database: test
      port: 27017
      
  logging:
    level:'[org.springframework.data.mongodb]': debug
      
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    
    
